#! /bin/sh
if [ ! -f ./go.mod ];then
  cp go.mod.base go.mod
fi
go get -t github.com/go-sql-driver/mysql
go get -t github.com/jinzhu/gorm
go get -t github.com/gin-gonic/gin
go get -t github.com/influxdata/influxdb1-client/v2
go get -t github.com/influxdata/influxdb1-client

go get -t github.com/globalsign/mgo
go get -t github.com/globalsign/mgo/bson
go get -t github.com/gorilla/mux
go get -t github.com/soniah/gosnmp

go get -t github.com/TylerBrock/colorjson

go get -t golang.org/x/crypto/bcrypt
go get -t github.com/dgrijalva/jwt-go

go get -t github.com/libvirt/libvirt-go
go get -t github.com/libvirt/libvirt-go-xml
go get -t github.com/digitalocean/go-libvirt
go get -t github.com/go-xmlfmt/xmlfmt

go get -t github.com/zquestz/ws-tcp-proxy
go get -t github.com/evangwt/go-vncproxy
go get -t golang.org/x/net/websocket

go get -t github.com/coreos/go-iptables/iptables

go get -t github.com/robfig/cron/v3@v3.0.0