#! /bin/sh
if [ ! -f ./go.mod ];then
  cp go.mod.base go.mod
fi
go get github.com/go-sql-driver/mysql
go get github.com/jinzhu/gorm
go get github.com/gin-gonic/gin
go get github.com/influxdata/influxdb1-client/v2
go get github.com/influxdata/influxdb1-client

go get github.com/globalsign/mgo
go get github.com/globalsign/mgo/bson
go get github.com/gorilla/mux
go get github.com/soniah/gosnmp

go get github.com/TylerBrock/colorjson

go get golang.org/x/crypto/bcrypt
go get github.com/dgrijalva/jwt-go

go get -t github.com/libvirt/libvirt-go
go get -t github.com/libvirt/libvirt-go-xml
go get -t github.com/digitalocean/go-libvirt
go get -t github.com/go-xmlfmt/xmlfmt

go get github.com/zquestz/ws-tcp-proxy