package insert

import (
	"cmpService/common/models"
	"time"
)

var newSubCodeData = []models.SubCode{
	{ID: 0, Code: models.Code{}, CodeID: 15, Name: "랙 없음", Order: 128},
	{0, models.Code{}, 16, "랙 없음", 189},
	{0, models.Code{}, 17, "랙 없음", 2},
	{0, models.Code{}, 18, "랙 없음", 2},
	{0, models.Code{}, 102, "랙 없음", 4},
	{0, models.Code{}, 438, "랙 없음", 3},
	{0, models.Code{}, 536, "랙 없음", 1},
	{0, models.Code{}, 544, "랙 없음", 1},
	{0, models.Code{}, 552, "랙 없음", 20},
	{0, models.Code{}, 574, "랙 없음", 2},
	{0, models.Code{}, 575, "랙 없음", 2},
	{0, models.Code{}, 613, "랙 없음", 2},
}

var newUsers = []models.User{
	{
		Idx:              0,
		UserId:           "bhjung",
		Password:         "nubes1510!#",
		Name:             "정병화",
		IsCompanyAccount: false,
		CompanyIdx:       0,
		Email:            "bhjung@nubes-bridge.com",
		AuthLevel:        5,
		Tel:              "02-1111-3333",
		HP:               "010-1111-3333",
		Zipcode:          "",
		Address:          "",
		AddressDetail:    "",
		TermDate:         time.Time{},
		BlockDate:        time.Time{},
		Memo:             "",
		WorkScope:        "",
		Department:       "",
		Position:         "",
		EmailAuth:        false,
		GroupEmailAuth:   false,
		Avata:            nil,
		RegisterDate:     time.Time{},
		LastAccessDate:   time.Time{},
		LastAccessIp:     "",
	},
	{
		Idx:              0,
		UserId:           "khlee",
		Password:         "nubes1510!#",
		Name:             "이경훈",
		IsCompanyAccount: false,
		CompanyIdx:       0,
		Email:            "khlee@nubes-bridge.com",
		AuthLevel:        10,
		Tel:              "02-1111-3333",
		HP:               "010-1111-3333",
		Zipcode:          "",
		Address:          "",
		AddressDetail:    "",
		TermDate:         time.Time{},
		BlockDate:        time.Time{},
		Memo:             "",
		WorkScope:        "",
		Department:       "",
		Position:         "",
		EmailAuth:        false,
		GroupEmailAuth:   false,
		Avata:            nil,
		RegisterDate:     time.Time{},
		LastAccessDate:   time.Time{},
		LastAccessIp:     "",
	},
	{
		Idx:              0,
		UserId:           "ebjee",
		Password:         "nubes1510!#",
		Name:             "지은빈",
		IsCompanyAccount: false,
		CompanyIdx:       0,
		Email:            "ebjee@nubes-bridge.com",
		AuthLevel:        10,
		Tel:              "02-1111-3333",
		HP:               "010-1111-3333",
		Zipcode:          "",
		Address:          "",
		AddressDetail:    "",
		TermDate:         time.Time{},
		BlockDate:        time.Time{},
		Memo:             "",
		WorkScope:        "",
		Department:       "",
		Position:         "",
		EmailAuth:        false,
		GroupEmailAuth:   false,
		Avata:            nil,
		RegisterDate:     time.Time{},
		LastAccessDate:   time.Time{},
		LastAccessIp:     "",
	},
	{
		Idx:              0,
		UserId:           "james",
		Password:         "nubes1510!#",
		Name:             "안종석",
		IsCompanyAccount: false,
		CompanyIdx:       0,
		Email:            "james@nubes-bridge.com",
		AuthLevel:        5,
		Tel:              "02-1111-3333",
		HP:               "010-1111-3333",
		Zipcode:          "",
		Address:          "",
		AddressDetail:    "",
		TermDate:         time.Time{},
		BlockDate:        time.Time{},
		Memo:             "",
		WorkScope:        "",
		Department:       "",
		Position:         "",
		EmailAuth:        false,
		GroupEmailAuth:   false,
		Avata:            nil,
		RegisterDate:     time.Time{},
		LastAccessDate:   time.Time{},
		LastAccessIp:     "",
	},
}

var newCompanies = []models.Company{
	{
		Idx:           0,
		Name:          "Nubes-Bridge",
		Email:         "nubes@nubes-bridge.com",
		Homepage:      "nubes-bridge.com",
		Tel:           "02-111-2222",
		HP:            "",
		Zipcode:       "",
		Address:       "",
		AddressDetail: "",
		TermDate:      time.Time{},
		IsCompany:     false,
		UserId:        "nubes",
		Memo:          "",
	},
}


