package mariadblayer

const (
	// TABLE
	ServerTable     = "device_server_tb d"
	NetworkTable    = "device_network_tb d"
	PartTable       = "device_part_tb d"
	ServerRawTable  = "device_server_tb"
	NetworkRawTable = "device_network_tb"
	PartRawTable    = "device_part_tb"
	CompanyRawTable = "company_tb"
	CodeRawTable    = "code_tb"
	CodeSubRawTable = "code_sub_tb"
	userTable	    = "user_tb"
	// SELECT
	PageSelectQuery             = "c1.c_name as manufacture_cd,s1.csub_name as model_cd,c2.c_name as device_type_cd,c3.c_name as ownership_cd,c4.c_name as ownership_div_cd,c5.c_name as idc_cd,s2.csub_name as rack_cd,cp1.cp_name as company_name,cp3.cp_name as owner_company_name,d.*"
	ServerSelectQuery           = "c1.c_name as manufacture_cd,s1.csub_name as model_cd,c2.c_name as device_type_cd,c3.c_name as ownership_cd,c4.c_name as ownership_div_cd,c5.c_name as idc_cd,s2.csub_name as rack_cd,cp1.cp_name as company_name,cp3.cp_name as owner_company_name,c6.c_name as size_cd,device_server_tb.*"
	NetworkSelectQuery          = "c1.c_name as manufacture_cd,s1.csub_name as model_cd,c2.c_name as device_type_cd,c3.c_name as ownership_cd,c4.c_name as ownership_div_cd,c5.c_name as idc_cd,s2.csub_name as rack_cd,cp1.cp_name as company_name,cp3.cp_name as owner_company_name,c6.c_name as size_cd,device_network_tb.*"
	PartSelectQuery             = "c1.c_name as manufacture_cd,s1.csub_name as model_cd,c2.c_name as device_type_cd,c3.c_name as ownership_cd,c4.c_name as ownership_div_cd,c5.c_name as idc_cd,s2.csub_name as rack_cd,cp1.cp_name as company_name,cp3.cp_name as owner_company_name,device_part_tb.*"
	SizeSelectQuery             = "c6.c_name as size_cd"
	CommentSelectQuery          = "cp2.cp_name as comment_register_id, device_comment_tb.*"
	CompanyAndUserIdSelectQuery = "company_tb.*, u.user_id"
	CodeAndSubCodeSelectQuery   = "c.c_Idx as c_idx, c.c_type as c_type, c.c_type_sub as c_type_sub, c.c_name as c_name, c.c_order as c_order, code_sub_tb.*"
	// JOIN
	ManufactureServerJoinQuery  = "LEFT JOIN code_tb AS c1 ON c1.c_type = 'device_server' AND c1.c_idx = d.manufacture_cd"
	ManufactureNetworkJoinQuery = "LEFT JOIN code_tb AS c1 ON c1.c_type = 'device_network' AND c1.c_idx = d.manufacture_cd"
	ManufacturePartJoinQuery    = "LEFT JOIN code_tb AS c1 ON c1.c_type = 'device_part' AND c1.c_idx = d.manufacture_cd"
	ModelJoinQuery              = "LEFT JOIN code_sub_tb AS s1 ON s1.csub_idx = d.model_cd"
	DeviceTypeServerJoinQuery   = "LEFT JOIN code_tb AS c2 ON c2.c_type = 'device_server' AND c2.c_idx = d.device_type_cd"
	DeviceTypeNetworkJoinQuery  = "LEFT JOIN code_tb AS c2 ON c2.c_type = 'device_network' AND c2.c_idx = d.device_type_cd"
	DeviceTypePartJoinQuery     = "LEFT JOIN code_tb AS c2 ON c2.c_type = 'device_part' AND c2.c_idx = d.device_type_cd"
	OwnershipJoinQuery          = "LEFT JOIN code_tb AS c3 ON c3.c_type = 'total' AND c3.c_idx = d.ownership_cd"
	OwnershipDivJoinQuery       = "LEFT JOIN code_tb AS c4 ON c4.c_type = 'total' AND c4.c_idx = d.ownership_div_cd"
	IdcJoinQuery                = "LEFT JOIN code_tb AS c5 ON c5.c_type = 'total' AND c5.c_idx = d.idc_cd"
	RackJoinQuery               = "LEFT JOIN code_sub_tb AS s2 ON s2.csub_idx = d.rack_cd"
	SizeJoinQuery               = "LEFT JOIN code_tb AS c6 ON c6.c_type = 'total' AND c6.c_idx = d.size_cd"
	CommentUserJoinQuery        = "LEFT JOIN user_tb u ON u.user_id = device_comment_tb.comment_register_id"
	CodeAndSubCodeJoinQuery     = "INNER JOIN code_tb c ON c.c_idx = code_sub_tb.c_idx"
	CompanyAndUserJoinQuery     = "INNER JOIN user_tb u ON u.cp_idx = company_tb.cp_idx"
	CompanyJoinQuery            = "LEFT JOIN company_tb cp1 ON cp1.cp_user_id = d.user_id"
	OwnerCompanyJoinQuery       = "LEFT JOIN company_tb cp3 ON cp3.cp_user_id = d.owner_company"
	CompanyAndCommentJoinQuery  = "LEFT JOIN company_tb cp2 ON cp2.cp_user_id = device_comment_tb.comment_register_id"
	// JOIN : no alias
	ManufactureServerNoAliasJoinQuery   = "LEFT JOIN code_tb AS c1 ON c1.c_type = 'device_server' AND c1.c_idx = device_server_tb.manufacture_cd"
	ManufactureNetworkNoAliasJoinQuery  = "LEFT JOIN code_tb AS c1 ON c1.c_type = 'device_network' AND c1.c_idx = device_network_tb.manufacture_cd"
	ManufacturePartNoAliasJoinQuery     = "LEFT JOIN code_tb AS c1 ON c1.c_type = 'device_part' AND c1.c_idx = device_part_tb.manufacture_cd"
	ModelServerNoAliasJoinQuery         = "LEFT JOIN code_sub_tb AS s1 ON s1.csub_idx = device_server_tb.model_cd"
	ModelNetworkNoAliasJoinQuery        = "LEFT JOIN code_sub_tb AS s1 ON s1.csub_idx = device_network_tb.model_cd"
	ModelPartNoAliasJoinQuery           = "LEFT JOIN code_sub_tb AS s1 ON s1.csub_idx = device_part_tb.model_cd"
	DeviceTypeServerNoAliasJoinQuery    = "LEFT JOIN code_tb AS c2 ON c2.c_type = 'device_server' AND c2.c_idx = device_server_tb.device_type_cd"
	DeviceTypeNetworkNoAliasJoinQuery   = "LEFT JOIN code_tb AS c2 ON c2.c_type = 'device_network' AND c2.c_idx = device_network_tb.device_type_cd"
	DeviceTypePartNoAliasJoinQuery      = "LEFT JOIN code_tb AS c2 ON c2.c_type = 'device_part' AND c2.c_idx = device_part_tb.device_type_cd"
	OwnershipServerNoAliasJoinQuery     = "LEFT JOIN code_tb AS c3 ON c3.c_type = 'total' AND c3.c_idx = device_server_tb.ownership_cd"
	OwnershipNetworkNoAliasJoinQuery    = "LEFT JOIN code_tb AS c3 ON c3.c_type = 'total' AND c3.c_idx = device_network_tb.ownership_cd"
	OwnershipPartNoAliasJoinQuery       = "LEFT JOIN code_tb AS c3 ON c3.c_type = 'total' AND c3.c_idx = device_part_tb.ownership_cd"
	OwnershipDivServerNoAliasJoinQuery  = "LEFT JOIN code_tb AS c4 ON c4.c_type = 'total' AND c4.c_idx = device_server_tb.ownership_div_cd"
	OwnershipDivNetworkNoAliasJoinQuery = "LEFT JOIN code_tb AS c4 ON c4.c_type = 'total' AND c4.c_idx = device_network_tb.ownership_div_cd"
	OwnershipDivPartNoAliasJoinQuery    = "LEFT JOIN code_tb AS c4 ON c4.c_type = 'total' AND c4.c_idx = device_part_tb.ownership_div_cd"
	OwnerCompanyServerNoAliasJoinQuery  = "LEFT JOIN company_tb cp3 ON cp3.cp_user_id = device_server_tb.owner_company"
	OwnerCompanyNetworkNoAliasJoinQuery = "LEFT JOIN company_tb cp3 ON cp3.cp_user_id = device_network_tb.owner_company"
	OwnerCompanyPartNoAliasJoinQuery    = "LEFT JOIN company_tb cp3 ON cp3.cp_user_id = device_part_tb.owner_company"
	IdcServerNoAliasJoinQuery           = "LEFT JOIN code_tb AS c5 ON c5.c_type = 'total' AND c5.c_idx = device_server_tb.idc_cd"
	IdcNetworkNoAliasJoinQuery          = "LEFT JOIN code_tb AS c5 ON c5.c_type = 'total' AND c5.c_idx = device_network_tb.idc_cd"
	IdcPartNoAliasJoinQuery             = "LEFT JOIN code_tb AS c5 ON c5.c_type = 'total' AND c5.c_idx = device_part_tb.idc_cd"
	RackServerNoAliasJoinQuery          = "LEFT JOIN code_sub_tb AS s2 ON s2.csub_idx = device_server_tb.rack_cd"
	RackNetworkNoAliasJoinQuery         = "LEFT JOIN code_sub_tb AS s2 ON s2.csub_idx = device_network_tb.rack_cd"
	RackPartNoAliasJoinQuery            = "LEFT JOIN code_sub_tb AS s2 ON s2.csub_idx = device_part_tb.rack_cd"
	SizeServerNoAliasJoinQuery          = "LEFT JOIN code_tb AS c6 ON c6.c_type = 'total' AND c6.c_idx = device_server_tb.size_cd"
	SizeNetworkNoAliasJoinQuery         = "LEFT JOIN code_tb AS c6 ON c6.c_type = 'total' AND c6.c_idx = device_network_tb.size_cd"
	CompanyServerNoAliasJoinQuery       = "LEFT JOIN company_tb cp1 ON cp1.cp_user_id = device_server_tb.user_id"
	CompanyNetworkNoAliasJoinQuery      = "LEFT JOIN company_tb cp1 ON cp1.cp_user_id = device_network_tb.user_id"
	CompanyPartNoAliasJoinQuery         = "LEFT JOIN company_tb cp1 ON cp1.cp_user_id = device_part_tb.user_id"
)
